strict-sigcheck = false

[YouTube]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YT-Music.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []

[YouTube-Experimental]
enabled = true
brand = "morphe-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
changelog-keywords = ["YouTube"]
arch = "arm64-v8a"
version = "21.26.360"

[YouTube-Experimental.patches]
"github:MorpheApp/morphe-patches" = { version = "latest", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[YT-Music-Experimental]
enabled = true
brand = "morphe-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
changelog-keywords = ["YouTube Music"]
arch = "arm64-v8a"
version = "9.26.51"

[YT-Music-Experimental.patches]
"github:MorpheApp/morphe-patches" = { version = "latest", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[Reddit-Experimental]
enabled = true
brand = "morphe-adobo-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "2026.27.0"

[Reddit-Experimental.patches]
"github:MorpheApp/morphe-patches" = { include = ["Disable play store updates"] }
"github:jkennethcarino/adobo" = { version = "dev", include = ["Hide awards", "Disable home feed auto-refresh", "Disable home screen redirect", "Colorize comment indent lines"], exclude = ["Disable home feed swipe", "Disable post detail swipe", "Disable screenshot banner", "Hide post view counts", "Hide Ask button from search bar", "Hide community highlights", "Hide prominent search bar", "Hide share count", "Hide upvote scores", "Hide user community badges", "Hide user flairs", "Open external links directly", "Remove ads and telemetry", "Sanitize share links"] }

[X-Twitter]
enabled = true
brand = "piko-x-shim"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
changelog-keywords = ["Twitter"]
version = "12.7.1-release.0"
arch = "arm64-v8a"

[X-Twitter.patches]
"github:crimera/piko" = { version = "dev", include = ["Browse tweet object"] }
"gitlab:inotia00/x-shim" = { version = "dev" }

[Instagram]
enabled = true
brand = "piko"
# github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
changelog-keywords = ["Instagram"]
arch = "arm64-v8a"

[Instagram.patches]
"github:crimera/piko" = { version = "dev", include = ["Clone"], exclude = ["Change version code"] }

[Niagara-Launcher]
enabled = true
exclusive-patches = true
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean/"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
changelog-keywords = ["Niagara Launcher"]
version = "latest"

[Niagara-Launcher.patches]
"github:hoo-dles/morphe-patches" = { version = "dev", include = ["Enable niagara pro", "Hide app icon"] }
"github:MorpheApp/morphe-patches" = ["Disable play store updates"]

[Pinterest]
enabled = true
Brand = "browzomje"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
changelog-keywords = ["Pinterest"]
version = "14.24.0"
arch = "arm64-v8a"

[Pinterest.patches]
"github:browzomje/browzomje-patches" = { version = "dev" }
"github:MorpheApp/morphe-patches" = ["Disable play store updates"]

[Gboard]
enabled = true
Brand = "Gboard-Adobo"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
changelog-keywords = ["Gboard"]
version =  "17.0.10.880768217-release-arm64-v8a"
arch = "arm64-v8a"

[Gboard.patches]
"github:jasonwu1994/Gboard-patches" = []
"github:jkennethcarino/adobo" = { version = "dev", include = ["Enable access points menu redesign", "Enable voice typing in incognito"], exclude = ["Always-incognito mode"] }
